asyncFuncTimeout: 1000
streamtags: []
functions:
  - id: eval
    filter: "true"
    disabled: null
    conf:
      add:
        - disabled: false
          name: id
          value: "'hello'"
groups: {}
