inputs:
  in_windows_metrics:
    disabled: false
    sendToRoutes: false
    type: windows_metrics
    persistence:
      enable: true
      maxDataSize: 100MB
    connections:
      - output: test
        pipeline: test-pipeline
